pleio_account/urls.py
from django.conf import settings
from django.conf.urls import include
from django.contrib.auth import views as auth_views
from django.views.decorators.clickjacking import xframe_options_exempt
from django.urls import path, URLPattern, URLResolver
from django.contrib import admin
from django.views.i18n import JavaScriptCatalog
from oauth2_provider import views as oauth2_views
from two_factor.urls import urlpatterns as tf_urls

from api import views as api_views
from core import views, forms
from core.class_views import (
    PleioLoginView,
    PleioSessionDeleteView,
    PleioSessionDeleteOtherView
)


class DecoratedURLPattern(URLPattern):
    def resolve(self, *args, **kwargs):
        result = super(DecoratedURLPattern, self).resolve(*args, **kwargs)
        if result:
            result.func = self._decorate_with(result.func)
        return result


class DecoratedRegexURLResolver(URLResolver):
    def resolve(self, *args, **kwargs):
        result = super(DecoratedRegexURLResolver, self) \
            .resolve(*args, **kwargs)
        if result:
            result.func = self._decorate_with(result.func)
        return result


def decorated_includes(func, includes):
    """
    Include URLconf from module but apply the specified decorator to each.
    """
    urlconf_module, app_name, namespace = includes
    urlconf_urls = urlconf_module.urlpatterns

    for item in urlconf_urls:
        if isinstance(item, URLPattern):
            item.__class__ = DecoratedURLPattern
            item._decorate_with = func
        elif isinstance(item, URLResolver):
            item.__class__ = DecoratedRegexURLResolver
            item._decorate_with = func

    return urlconf_module, app_name, namespace


urlpatterns = [
    path('register/', views.register, name='register'),
    path(
        'register/complete/',
        views.register_complete,
        name='register_complete'
    ),
    path(
        'register/activate/<activation_token>/',
        views.register_activate,
        name='register_activate'
    ),
    path('termsofuse/', views.terms_of_use, name='terms_of_use'),
    path(
        'securitypages/<page_action>/',
        views.security_pages,
        name='security_pages'
    ),
    path('securitypages/', views.security_pages, name='security_pages'),
    path(
        'security-questions/',
        views.set_security_question,
        name='set-questions'
    ),
    path(
        'login/',
        PleioLoginView.as_view(),
        name='login'
    ),
    path('logout/', views.logout, name='logout'),
    path('profile/', views.profile, name='profile'),
    path(
        'accept_previous_logins/<acceptation_token>/',
        views.accept_previous_login,
        name='accept_previous_login'
    ),
    path(
        'account/sessions/other/delete/',
        view=PleioSessionDeleteOtherView.as_view(),
        name='session_delete_other'
    ),
    path(
        'account/sessions/<pk>/delete/',
        view=PleioSessionDeleteView.as_view(),
        name='session_delete'
    ),
    path(
        'oauth/v2/authorize',
        oauth2_views.AuthorizationView.as_view(),
        name='authorize'
    ),
    path('oauth/v2/token', oauth2_views.TokenView.as_view(), name='token'),
    path(
        'oauth/v2/revoke_token',
        oauth2_views.RevokeTokenView.as_view(),
        name='revoke-token'
    ),
    path('api/users/me', api_views.me, name='me'),
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('i18n/', include('django.conf.urls.i18n')),
    path('freshdesk/', views.freshdesk_sso, name='freshdesk_sso'),
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    # Overriding some of the built-in contrib.auth views to use our templates
    # instead.
    path(
        'password_reset/',
        forms.ResetPasswordRequestView.as_view(),
        name='password_reset'
    ),
    path(
        'password_reset/done/',
        auth_views.PasswordResetDoneView.as_view(),
        {
            'template_name': 'password_reset_done.html'
        },
        name='password_reset_done'
    ),
    path(
        'password_reset/questions/',
        views.security_questions,
        name='password_reset_questions'
    ),
    path(
        'reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(),
        {
            'template_name': 'password_reset_confirm.html'
        },
        name='password_reset_confirm'
    ),
    path(
        'reset/done/',
        auth_views.PasswordResetCompleteView.as_view(),
        {
            'template_name': 'password_reset_complete.html'
        },
        name='password_reset_complete'
    ),
    # django-two-factor
    path('', include(tf_urls)),
    # django-user-sessions
    path('', include('user_sessions.urls', 'user_sessions')),
    # django-oidc-provider
    path('openid/', decorated_includes(
      xframe_options_exempt,
      include('oidc_provider.urls', namespace='oidc_provider')
    ))
]

if settings.DEBUG:
    import debug_toolbar
    from django.conf.urls.static import static

    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls))
    ]

core/models.py
import json
from django.contrib.admin import ModelAdmin
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.contrib.auth.hashers import check_password
from django.utils import timezone
from django.utils.text import slugify
from django.core import signing
from django.core.mail import send_mail
from django.contrib import admin
from django.contrib.sites.shortcuts import get_current_site
from django.db import models
from django.template.loader import render_to_string
from constance import config

from .helpers import unique_filepath
from .login_session_helpers import (
    get_city,
    get_country,
    get_device,
    get_lat_lon
)


class Manager(BaseUserManager):
    def create_user(self, email, name, password=None, accepted_terms=False,
                    receives_newsletter=True):
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),
            name=name
        )

        user.set_password(password)
        user.accepted_terms = accepted_terms
        user.receives_newsletter = receives_newsletter

        user.save(using=self._db)
        return user

    def create_superuser(self, email, name, password):
        user = self.create_user(
            email=self.normalize_email(email),
            name=name,
            password=password
        )

        user.is_admin = True
        user.is_active = True
        user.receives_newsletter = True

        user.save(using=self._db)
        return user


class User(AbstractBaseUser):
    objects = Manager()
    username = models.SlugField(unique=True)
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=255, unique=True)
    accepted_terms = models.BooleanField(default=False)
    receives_newsletter = models.BooleanField(default=True)
    avatar = models.ImageField(
        upload_to=unique_filepath,
        null=True,
        blank=True
    )

    is_active = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)

    REQUIRED_FIELDS = ['name']
    USERNAME_FIELD = 'email'

    def save(self, *args, **kwargs):
        if not self.username:
            self.username = self._get_unique_username()

        super(User, self).save(*args, **kwargs)

    def __str__(self):
        return self.email

    def _get_unique_username(self):
        max_length = User._meta.get_field('username').max_length
        username = slugify(self.email.split("@")[0])
        unique_username = username[:max_length]
        i = 1

        while User.objects.filter(username=unique_username).exists():
            unique_username = '{}-{}'.format(
                username[:max_length - len(str(i)) - 1],
                i
            )
            i += 1

        return unique_username

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    def get_full_name(self):
        return self.name

    def get_short_name(self):
        return self.name

    def email_user(self, subject, message, **kwargs):
        send_mail(subject, message, config.EMAIL_FROM, [self.email], **kwargs)

    def send_activation_token(self, request):
        current_site = get_current_site(request)

        template_context = {
            'user': self,
            'activation_token': signing.dumps(obj=self.email),
            'protocol': 'https' if request.is_secure() else 'http',
            'domain': current_site.domain
        }
        self.email_user(
            render_to_string('emails/register_subject.txt', template_context),
            render_to_string('emails/register.txt', template_context),
            html_message=render_to_string(
                'emails/register.html',
                template_context
            ),
            fail_silently=config.EMAIL_FAIL_SILENTLY
        )

    def activate_user(self, activation_token):
        try:
            email = signing.loads(
                activation_token,
                max_age=config.ACCOUNT_ACTIVATION_DAYS * 86400
            )

            if email is None:
                return None

            self = User.objects.get(email=email)

            if self.is_active:
                return None

            self.is_active = True
            self.save()
            #valid_user is the routing followed by name, email and id
            data = json.dumps({'name': self.name, 'email':self.email, 'id': self.id })
            routing = 'user.new'
            mq_newuser(routing,data)
            return self

        except (signing.BadSignature, User.DoesNotExist):
            return None

    def check_users_previous_logins(self, request):
        send_suspicious_behavior_warnings = self.receives_newsletter
        result = True

        try:
            device_id = request.session['device_id']
            login = self.previous_logins.get(device_id=device_id)
            previous_login_present = login.confirmed_login
        except Exception:
            previous_login_present = False

        if previous_login_present:
            # cookie is present so no need to send an email and no further
            # checking is requiered
            send_suspicious_behavior_warnings = False
            login.update_previous_login(request)

        if send_suspicious_behavior_warnings:
            if not self.logged_in_previously(request):
                # no confirmed matching login found, so email must be sent
                self.send_suspicious_login_message(request)
                result = False

        return result

    def logged_in_previously(self, request):
        # check whether user has previously logged in from this location and
        # using this device
        session = request.session

        login = self.previous_logins.filter(
            ip=session.ip,
            user_agent=get_device(session.user_agent)
        )

        known_login = (login.count() > 0)

        if not known_login:
            # request.user is atm still "Anonymoususer", so have to add self as
            # second arg
            PreviousLogins.add_known_login(request, self)
        else:
            login[0].update_previous_login(request)

        login = login.filter(confirmed_login=True)
        confirmed_login = (login.count() > 0)

        return confirmed_login

    def send_suspicious_login_message(self, request):
        session = request.session
        current_site = get_current_site(request)

        template_context = {
            'user': self,
            'city': get_city(session.ip),
            'country': get_country(session.ip),
            'user_agent': session.user_agent,
            'protocol': 'https' if request.is_secure() else 'http',
            'domain': current_site.domain
        }

        self.email_user(
            render_to_string(
                'emails/suspicious_login_subject.txt',
                template_context
            ),
            render_to_string(
                'emails/suspicious_login.txt',
                template_context
            ),
            html_message=render_to_string(
                'emails/suspicious_login.html',
                template_context
            ),
            fail_silently=config.EMAIL_FAIL_SILENTLY
        )

    @property
    def is_staff(self):
        return self.is_admin

    @property
    def is_superuser(self):
        return self.is_admin


from django.contrib.auth.admin import UserAdmin


class UserAdmin(UserAdmin):
    search_fields = ModelAdmin.search_fields + ('username', 'name', 'email',)
    list_filter = ModelAdmin.list_filter + ('is_active', 'is_admin',)
    list_display = ModelAdmin.list_display + ('is_active', 'id',)
    filter_horizontal = ()
    ordering = ('-id', )
    fieldsets = add_fieldsets = (
        (None, {
            'fields': ('last_login', 'name', 'email', 'password', 'avatar',)
        }),
        ('Settings', {
            'fields': (
                'accepted_terms',
                'receives_newsletter',
                'is_active',
                'is_admin',
            )
        }),
    )


class PreviousLogins(models.Model):
    user = models.ForeignKey('User', on_delete=models.CASCADE, db_index=True, related_name='previous_logins')
    device_id = models.CharField(max_length=40, editable=False, null=True, db_index=True)
    ip = models.GenericIPAddressField(null=True, blank=True, verbose_name='IP')
    user_agent = models.CharField(null=True, blank=True, max_length=200)
    city = models.CharField(null=True, blank=True, max_length=100)
    country = models.CharField(null=True, blank=True, max_length=100)
    latitude = models.DecimalField(max_digits=5, decimal_places=3, null=True)
    longitude = models.DecimalField(max_digits=6, decimal_places=3, null=True)
    last_login_date = models.DateTimeField(default=timezone.now)
    confirmed_login = models.BooleanField(default=False)

    def add_known_login(request, user):
        session = request.session
        device_id = request.session['device_id']

        lat_lon = get_lat_lon(session.ip)
        try:
            latitude = lat_lon[0]
            longitude = lat_lon[1]
        except:
            latitude = None
            longitude = None

        login = PreviousLogins.objects.create(
            user = user,
            device_id =  device_id,
            ip = session.ip,
            user_agent = get_device(session.user_agent),
            city = get_city(session.ip),
            country = get_country(session.ip),
            latitude = latitude,
            longitude = longitude,
         )
        login.save()

    def update_previous_login(self, request):
        session = request.session

        try:
            self.last_login_date = timezone.now()
            self.ip = session.ip
            self.user_agent = get_device(session.user_agent)
            self.city = get_city(session.ip)

core/templates/backup_tokens.html
{% extends "base_account.html" %}
{% load i18n %}

{% block content %}
<h2>{% trans "Backup Tokens" %}</h2>
 <form method="post">{% csrf_token %}{{ form }}
     <div class="account__cards">
         <div class="card ___nopadding">
            <h2 class="card__title ___addpadding-side">{% block title %}{% trans "Backup tokens" %}{% endblock %}</h2>
            <div class="___addpadding-side">
                <p>{% blocktrans %}Backup tokens can be used when your primary and backup
                    phone numbers aren't available. The backup tokens below can be used
                    for login verification. If you've used up all your backup tokens, you
                    can generate a new set of backup tokens. Only the backup tokens shown
                    below will be valid.{% endblocktrans %}</p>
                    {% if device.token_set.count %}
                    <ul class="___inline">
                        {% for token in device.token_set.all %}
                        <li>
                            <span class="badge ___tag grey">{{ token.token }}</span>
                        </li>
                        {% endfor %}
                    </ul>
                    <br />
                    <p>{% blocktrans %}Print these tokens and keep them somewhere safe.{% endblocktrans %}</p>
                    {% else %}
                    <p>{% trans "You don't have any backup codes yet." %}</p>
                    {% endif %}
                </div>
                <div class="card__action ___addpadding-side">
                    <button class="button ___clear" type="submit">{% trans "Generate tokens" %}</button>
                </div>
         </div>
     </div>
  </form>
{% endblock %}

core/templates/base.html
{% load render_bundle from webpack_loader %}
{% load i18n %}
{% load Pleio_templatetags %}
{% load app_customization %}
{% get_current_language as LANGUAGE_CODE %}


<!DOCTYPE html>
<html lang="{{ request.COOKIES.lang }}">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title> {{ app.APP_TITLE }} - {% block page_title %}{% endblock %}</title>
        <meta name="viewport" content="width=device-width,height=device-height,user-scalable=no,initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0">
        <meta property="og:title" content="{{ app.APP_TITLE }}">
        <meta property="og:image" content="{{ request.scheme }}://{{ request.get_host }}{{ MEDIA_URL }}{{ app.APP_LOGO }}">
        <meta property="og:url" content="{{ request.scheme }}://{{ request.get_host }}{{ request.get_full_path }}">
        <link href="//fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i" rel="stylesheet">
        <link rel="icon" href="{{ MEDIA_URL }}{{ app.APP_FAVICON }}">
        {% render_bundle "web" "css" %}
        <script src='https://www.google.com/recaptcha/api.js'></script>
	    <link rel="stylesheet" type="text/css" href="/static/semantic/dist/semantic.min.css">
    </head>
    <body>
        <div class="account-overlay  ui container">

            {% if request.COOKIES.partner_site_url %}
                <div class="account-theme" data-bg="{{ request.COOKIES.partner_site_logo_url }}">
            {% else %}
                <div class="account-theme">
            {% endif %}

                {% if request.COOKIES.partner_site_url %}
                    <a href={{ request.COOKIES.partner_site_url }} class="button ___white ___outline account__close">{{ request.COOKIES.partner_site_name }}</a>
                {% endif %}
            </div>

            <div class="account">
                <div class="account__top-bar">
                    <a href="{% url 'login' %}" style="color:black;">
                        <img alt ="" src="{{ MEDIA_URL }}{{ app.APP_URL }}" class="ui top aligned mini image header-logo">
                        <span class="ui huge header">
                            {{ app.APP_TITLE }}
                        </span>
                    </a>
                    {% comment 'removing for now' %}
                    <a class="navigation__logo" title="{% trans "Back to the homepage" %}" href="https://www.pleio.nl/">{% include_asset "images/logo.svg" %}</a>
                    {% endcomment %}

                    {% if app.APP_LANGUAGE_TOGGLE %}
                      <div class="language-toggle">
                          {% include "language.html" %}
                      </div>
                    {% endif %}
                </div>

                <main>
                  <div class="ui grid" style="padding-top:40px">
                      <div id="base-card" class="ui centered raised card">
                          <div class="content">
                              {% block content %}{% endblock %}
                          </div>
                      </div>
                  </div>
                </main>

                <footer class="account__fip" style="margin-top:120px; border-top:1px solid rgba(34,36,38,.15);">
                    <div style="margin-bottom:20px">
                        <ul class="u horizontal list">
                            {% if app.APP_HELPDESK_LINK %}
                              <li class="item">
                                  <a href="{{ app.APP_HELPDESK_LINK }}">{% trans "Help / Contact Us" %}</a>
                              </li>
                            {% endif %}
                            <li class="item">
                                <a class="terms_link" target="_blank" href="https://gccollab.ca/terms">{% trans "Terms and Conditions" %}
                                  <span aria-hidden="true">{% include_asset "icons/external.svg" %}</span><span class="invisible">{% trans "Opens in a new tab" %}</span></a>
                            </li>
                        </ul>
                    </div>
                    <div style="margin-bottom:10px;">
                        {% if app.APP_FOOTER_IMAGE_LEFT %}
                        <div class="left floated fip__signature" style="height:22px; float:left;">
                            <img alt="" src="{{ MEDIA_URL }}{{ app.APP_FOOTER_IMAGE_LEFT }}">
                        </div>
                        {% endif %}
                        {% if app.APP_FOOTER_IMAGE_RIGHT %}
                        <div class="right floated fip__watermark">
                            <img alt="" src="{{ MEDIA_URL }}{{ app.APP_FOOTER_IMAGE_RIGHT }}">
                        </div>
                        {% endif %}
                    </div>
                </footer>
            </div>
        </div>

	<style>
.account {
padding-top:2rem;
}
.navigation__logo {
display:block;
width: 200px;
padding-bottom: 1rem;
}
.account__top-bar {
padding-bottom:2rem;
}
	  body {
	    background: #FAFAFA;
        background-image: {% show_customizations_bg_image %}
	  }
	  fieldset {
	    padding: .35em 0 .625em;
	    border:none;
	  }
	  .ui.checkbox label {
	    cursor:pointer;
	  }
.field {
position:relative;
}

.show svg {
    fill: {{ app.APP_BRAND_COLOR }};
}

.ui.primary.button, .ui.primary.button:active{
    background-color: {{ app.APP_BRAND_COLOR }};
}

.ui.primary.button:hover{
    background-color: {{ app.APP_BRAND_COLOR }};
    opacity: 0.8;
}

.text_grey{
    color:#545454;
}

.small_text{
    font-size:0.90em;
}
	</style>

        <script src="https://www.google.com/recaptcha/api.js"></script>
        <script src="//code.jquery.com/jquery-3.1.1.min.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/js/materialize.min.js"></script>
        {% render_bundle "vendor" "js" %}
        {% render_bundle "web" "js" %}

	<script
	  src="https://code.jquery.com/jquery-3.1.1.min.js"
	  integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
	  crossorigin="anonymous"></script>
	<script src="/static/semantic/dist/semantic.min.js"></script>
    </body>
</html>

core/templates/language.html

{% load i18n %}

{% comment %}
<a href="{{ current_path }}" class="ui primary button compact" onclick="changeLanguage();" id='btn' title="{% trans "Change language" %}">
        {% get_current_language as LANGUAGE_CODE %}
        {% get_available_languages as LANGUAGES %}
        {% for langs in LANGUAGES %}
            <span>{{ langs.0 }}</span> </br>
        {% endfor %}
      {% if request.COOKIES.lang == 'en'%}
        <span aria-hidden="true">FR</span>
        <span class="invisible" lang="fr">Français</span>
      {% else %}
        <span aria-hidden="true">EN</span>
        <span class="invisible" lang="en">English</span>
      {% endif %}
    </a>
{% endcomment %}
<form action="{% url 'set_language' %}" method="post">
    {% csrf_token %}
    <label aria-hidden="true" type="hidden">
        <input name="next" type="hidden" value="{{ redirect_to }}" />
    </label>
    <div class="">
        {% get_current_language as LANGUAGE_CODE %}
        {% get_available_languages as LANGUAGES %}
        {% if LANGUAGES|length < 3 %}
            {% for langs in LANGUAGES %}
                {% if langs.0 != LANGUAGE_CODE %}
                    <button type="submit"
                    name="language"
                    value="{{ langs.0 }}"
                    class="ui primary button compact"
                    onclick="changeLanguage('{{ langs.0 }}');">
                    {{ langs.0|upper }}
                    </button>
                {% endif %}  
            {% endfor %}
        {% else %}
        <div class="ui dropdown item">
            {{ LANGUAGE_CODE|language_name_translated }}
            <i class="dropdown icon"></i>
            <div class="menu" title="{% trans "Change language" %}">
                
                {% for langs in LANGUAGES %}
                    <button type="submit"
                    name="language"
                    value="{{ langs.0 }}"
                    class="item"
                    onclick="changeLanguage('{{ langs.0 }}');">
                    {{ langs.0|upper }}
                    </button>
                {% endfor %}
            </div>
        </div>
        {% endif %}
    </div>
</form>

<script>

function changeLanguage(lang) {
    console.log('my lang'+lang);
    $.ajax({
        type: "POST",
        url: "{% url 'set_language' %}",
        data: {'language': lang, 'csrfmiddlewaretoken': '{{ csrf_token }}'},
        success: function(response) {
            setLangCookie(lang);
            console.log('set cookie '+lang);
        },
        error: function(rs, e) { console.log(e); }
    });    
}    
function getCookie(cname) {
    var lang = "";
    var name = cname + "=";
    var decodedCookie = decodeURIComponent(document.cookie);
    var ca = decodedCookie.split(';');
    for(var i = 0; i <ca.length; i++) {
        var c = ca[i];
        while (c.charAt(0) == ' ') {
            c = c.substring(1);
        }
        if (c.indexOf(name) == 0) {
            //return c.substring(name.length, c.length);
            lang = c.substring(name.length, c.length);
        }
    }
    return lang;
}

function setLangCookie(lang) {
    var hostname = location.hostname;
    var length = hostname.split(".").length - 1;
    var domain = (length >= 2) ? '.' + hostname.split('.').slice(-2).join('.') : hostname;
    setCookie("lang", lang, '', '/', domain);
}

function setCookie(sName, sValue, oExpires, sPath, sDomain, bSecure) {
    var sCookie = sName + "=" + encodeURIComponent(sValue);
    if (oExpires) {
        sCookie += "; expires=" + oExpires.toGMTString();
    }
    if (sPath) {
        sCookie += "; path=" + sPath;
    }
    if (sDomain) {
        sCookie += "; domain=" + sDomain;
    }
    if (bSecure) {
        sCookie += "; secure";
    }
    document.cookie = sCookie;

    $.ajax({
        type: "POST",
        url: "{% url 'set_language' %}",
        data: {'language': sValue, 'csrfmiddlewaretoken': '{{ csrf_token }}'},
        success: function(response) {},
        error: function(rs, e) { console.log(e); }
    });

}
</script>

core/templates/partner_links.html
<div class="ui secondary labeled icon menu" style="flex-wrap:wrap;">
    {% for partner in partners %}
    <a class="item" href="{{partner.partner_site_url}}">
        <img alt="{{partner.partner_site_name}}" aria-hidden="true" src="{{partner.partner_site_logo_url}}" class="app_icon" style="margin-bottom: 5px; padding-right:0;"></img>
        {{partner.partner_site_name}}
    </a>
    {% endfor %}
</div>

core/templates/password_reset_done.html
{% extends "base.html" %}
{% load i18n %}
{% load Pleio_templatetags %}

{% block page_title %}
{% trans "Email sent" %}
{% endblock %}

{% block content %}
    <div class="login__step-title">
        <div>
            <h1 class="ui large header">{% trans "Forgot password" %}</h1>

        </div>
        <!--<img src="/static/images/logo-icon.svg" class="login__step-icon"/>-->
    </div>

    <div class="messages correct ui positive message">
        <div class="messages__link content">
            <div class="textcolor_primary header">{% trans "Email sent" %}</div>
            <p class="textcolor_secondary">{% trans "You will receive an email with a link to set a new password in the next 20 minutes. Please check your junk folder." %} </p>
        </div>
    </div>

    <div class="register_block" style="margin-bottom:15px;">
      <span>{% trans "Don't have access to the registered email address?" %}</span>
      <a class="item" href="{% url 'password_reset_questions' %}">{% trans "Use security questions to reset your password"%}</a>
    </div>

    <div class="register__buttons">
        <a href="{% url 'login' %}" >{% trans "Return to sign in" %}</a>
    </div>
{% endblock %}

core/templates/profile.html
{% extends "base_account.html" %}
{% load i18n %}
{% load Pleio_templatetags %}

{% block page_title %}{% trans "Account Settings" %}{% endblock %}

{% block page_header %}{% trans "Account Settings" %}{% endblock %}

{% block content %}
    <h2 class="ui header">{% trans "Profile" %}</h2>

    <form enctype="multipart/form-data" method="post" action="." class="ui form">
        <div class="account__cards ui cards">
            <div class="card ___nopadding ui card">
		<div class="content">
                {% csrf_token %}
                <h3 class="card__title ___addpadding-side header">{% trans "Your details" %}</h3>
                <fieldset class="___addpadding-side">
                    <div class="field">
                        <label for="id_name">{% trans "Name" %}</label>
                        {{ form.errors.name }}
                        {{ form.name }}
                    </div>
                    <div class="field">
                        <label for="id_email">{% trans "Email" %}</label>
                        {{ form.errors.email }}
                        {{ form.email }}
                        <!--<span class="badge green __uppercase ui label"><i class="icon">{% include_asset "icons/check.svg" %}</i>{% trans "Government" %}</span>-->
                    </div>
                    <div class="field ui checkbox">
                        {{ form.errors.receives_newsletter }}
                        {{ form.receives_newsletter }}
                        <label for="id_receives_newsletter">{% trans "Receive Suspicious Sign In Emails" %}</label>
                    </div>
                </fieldset>
		</div>
                <div class="card__action ___addpadding-side extra content">
                    <button name="update" class="button ___clear ui button right floated primary" type="submit">{% trans "Save" %}</button>
                </div>

            </div>
        </div>


    </form>

{% endblock %}

core/templates/register_activate.html
{% extends "base.html" %}
{% load i18n %}
{% load Pleio_templatetags %}

{% block page_title %}
{% trans "Activation error" %}
{% endblock %}

{% block content %}
    <h1 class="ui large header">{% trans "Activation error" %}</h1>
    <div class="messages ui error">
        <i class="icon" aria-hidden="true">{% include_asset "icons/account-alert.svg" %}<i>
        <div class="content">
            <div class="textcolor_primary">{% trans "We could not activate your account" %}</div>
            <div class="textcolor_secondary">{% trans "Your account may already be activated." %} </div>
        </div>
    </div>
    <a href="{% url 'login' %}" >{% trans "Return to sign in" %}</a>
{% endblock %}